# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#        main:
#            id: fos_user.user_provider.username
            #entity:
            #    class: UserBundle:User
            #    property: username

    encoders:
        Starter\UserBundle\Entity\User: sha512
            #algorithm: sha512
            #iterations: 9616
            #encode_as_base64: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path:            core_homepage
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login

            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
