recup_homepage:
    path:     /administration/recuperation
    defaults: { _controller: AxiaRecupBundle:Recup:index }

recup_parts:
    path:     /administration/parts
    defaults: { _controller: AxiaRecupBundle:Recup:parts }
    options:
        expose: true

recup_all:
    path:     /administration/recup_all
    defaults: { _controller: AxiaRecupBundle:Recup:recup_all }
    options:
        expose: true

recup_single:
    path:     /administration/recup_single
    defaults: { _controller: AxiaRecupBundle:Recup:recup_single }
    options:
        expose: true

recup_update:
    path:     /administration/recuperation/update
    defaults: { _controller: AxiaRecupBundle:Update:index }

recup_update_parts:
    path:     /administration/update/parts
    defaults: { _controller: AxiaRecupBundle:Update:parts }
    options:
        expose: true

update_all:
    path:     /administration/update_all
    defaults: { _controller: AxiaRecupBundle:Update:recup_all }
    options:
        expose: true

update_all_auto:
    path:     /administration/update/auto
    defaults: { _controller: AxiaRecupBundle:Update:auto }

update_single:
    path:     /administration/update_single
    defaults: { _controller: AxiaRecupBundle:Update:recup_single }
    options:
        expose: true