<?php

namespace Axia\RecupBundle\Repository;

/**
 * TempoEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempoEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
